# Generated by Django 4.0.4 on 2025-07-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_remove_project_author_delete_article_delete_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageExemple',
        ),
    ]
