# Generated by Django 4.0.4 on 2022-05-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0005_pageexemple_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageexemple',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pageexemple',
            name='date',
            field=models.DateField(auto_created=True, default='2022-05-23', verbose_name='Date de mise en place du site'),
        ),
        migrations.AlterField(
            model_name='pageexemple',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sites/'),
        ),
    ]
