# Generated by Django 4.0.4 on 2022-05-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0006_pageexemple_description_alter_pageexemple_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageexemple',
            name='prix',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pageexemple',
            name='date',
            field=models.DateField(auto_created=True, auto_now_add=True, verbose_name='Date de mise en place du site'),
        ),
    ]
