# Generated by Django 4.0.4 on 2022-05-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0007_pageexemple_prix_alter_pageexemple_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageexemple',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
