# Generated by Django 4.0.4 on 2022-05-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0008_alter_pageexemple_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageexemple',
            name='prix',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
