# Generated by Django 4.0.4 on 2024-03-02 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('slug_name', models.SlugField(primary_key=True, serialize=False)),
                ('summup', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to='article_images/')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='date last modified')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
