# Generated by Django 4.0.4 on 2024-05-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_summup_post_is_visible_alter_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Est visible'),
        ),
    ]
